# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.3'
  displayName: 'Install Node'

- script: yarn install
  displayName: 'Install Node dependencies'

- script: npm install -g expo-cli
  displayName: 'Install Expo CLI'

- script: expo login -u ${EXPO_USERNAME} -p ${EXPO_PASSWORD}
  displayName: 'Expo login'

- script: expo eject --eject-method expokit --non-interactive
  displayName: 'Expo eject'

- script: cd ios && pods install && cd ..
  displayName: 'Install pods'